spring.application.name=questflow

spring.datasource.url=jdbc:postgresql://localhost:5430/questflow
spring.datasource.username=questflow
spring.datasource.password=questflow

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true